// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: plugin/proto/comparator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComparatorPlugin_Compare_FullMethodName = "/proto.ComparatorPlugin/Compare"
)

// ComparatorPluginClient is the client API for ComparatorPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ComparatorPlugin defines the gRPC service for comparing HTTP responses
type ComparatorPluginClient interface {
	// Compare compares two HTTP responses and returns the result
	Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error)
}

type comparatorPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewComparatorPluginClient(cc grpc.ClientConnInterface) ComparatorPluginClient {
	return &comparatorPluginClient{cc}
}

func (c *comparatorPluginClient) Compare(ctx context.Context, in *CompareRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, ComparatorPlugin_Compare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComparatorPluginServer is the server API for ComparatorPlugin service.
// All implementations must embed UnimplementedComparatorPluginServer
// for forward compatibility.
//
// ComparatorPlugin defines the gRPC service for comparing HTTP responses
type ComparatorPluginServer interface {
	// Compare compares two HTTP responses and returns the result
	Compare(context.Context, *CompareRequest) (*CompareResponse, error)
	mustEmbedUnimplementedComparatorPluginServer()
}

// UnimplementedComparatorPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComparatorPluginServer struct{}

func (UnimplementedComparatorPluginServer) Compare(context.Context, *CompareRequest) (*CompareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compare not implemented")
}
func (UnimplementedComparatorPluginServer) mustEmbedUnimplementedComparatorPluginServer() {}
func (UnimplementedComparatorPluginServer) testEmbeddedByValue()                          {}

// UnsafeComparatorPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComparatorPluginServer will
// result in compilation errors.
type UnsafeComparatorPluginServer interface {
	mustEmbedUnimplementedComparatorPluginServer()
}

func RegisterComparatorPluginServer(s grpc.ServiceRegistrar, srv ComparatorPluginServer) {
	// If the following call pancis, it indicates UnimplementedComparatorPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComparatorPlugin_ServiceDesc, srv)
}

func _ComparatorPlugin_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComparatorPluginServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComparatorPlugin_Compare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComparatorPluginServer).Compare(ctx, req.(*CompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComparatorPlugin_ServiceDesc is the grpc.ServiceDesc for ComparatorPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComparatorPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ComparatorPlugin",
	HandlerType: (*ComparatorPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compare",
			Handler:    _ComparatorPlugin_Compare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/proto/comparator.proto",
}
